// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlPcJBwImqOPuNgmUOPSngXCBm467hLX8',
    appId: '1:742372385790:web:f2d4d1e3050e2f052456af',
    messagingSenderId: '742372385790',
    projectId: 'auth01-922af',
    authDomain: 'auth01-922af.firebaseapp.com',
    storageBucket: 'auth01-922af.appspot.com',
    measurementId: 'G-78TBSR6RK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNCNDJi-XaLIQokTZHoo86dfWWudZiZs',
    appId: '1:742372385790:android:840b2c85016920612456af',
    messagingSenderId: '742372385790',
    projectId: 'auth01-922af',
    storageBucket: 'auth01-922af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgbi-s_8sJZoZf3sEsu1d5c3m1q17cU7k',
    appId: '1:742372385790:ios:59d25b395e05017d2456af',
    messagingSenderId: '742372385790',
    projectId: 'auth01-922af',
    storageBucket: 'auth01-922af.appspot.com',
    iosBundleId: 'com.example.assignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgbi-s_8sJZoZf3sEsu1d5c3m1q17cU7k',
    appId: '1:742372385790:ios:05b72608cbb22df82456af',
    messagingSenderId: '742372385790',
    projectId: 'auth01-922af',
    storageBucket: 'auth01-922af.appspot.com',
    iosBundleId: 'com.example.assignment3.RunnerTests',
  );
}
